config/routes.rb
Rails.application.routes.draw do
  get "forecasts/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "forecasts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  def index
    # If Geocoder can't find your location, then view New York's
    browser_location = request.location.postal_code || "New York"
    location = params[:q].present? ? params[:q] : browser_location
    @forecast_data = WeatherApiService.new(location).request_forecast_data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6 col-xl-4">
      <%= form_with url: forecasts_index_path, method: :get do |form| %>
        <div class="input-group mt-5 mb-3">
          <%= form.text_field :q, { class: "form-control", placeholder: "Search by city or zip", aria: { label: "Search for address by zip or city name", describedby: "basic-addon2" } } %>
          <span class="input-group-text" id="basic-addon2" title="<%= @forecast_data[:live_request] ? "Cache miss, Live Request" : "Cache HIT!" %>">
            <% if @forecast_data[:live_request] %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-broadcast-pin" viewBox="0 0 16 16">
                <path d="M3.05 3.05a7 7 0 0 0 0 9.9.5.5 0 0 1-.707.707 8 8 0 0 1 0-11.314.5.5 0 0 1 .707.707zm2.122 2.122a4 4 0 0 0 0 5.656.5.5 0 1 1-.708.708 5 5 0 0 1 0-7.072.5.5 0 0 1 .708.708zm5.656-.708a.5.5 0 0 1 .708 0 5 5 0 0 1 0 7.072.5.5 0 1 1-.708-.708 4 4 0 0 0 0-5.656.5.5 0 0 1 0-.708zm2.122-2.12a.5.5 0 0 1 .707 0 8 8 0 0 1 0 11.313.5.5 0 0 1-.707-.707 7 7 0 0 0 0-9.9.5.5 0 0 1 0-.707zM6 8a2 2 0 1 1 2.5 1.937V15.5a.5.5 0 0 1-1 0V9.937A2 2 0 0 1 6 8z"/>
              </svg>
            <% else %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-database" viewBox="0 0 16 16">
                <path d="M4.318 2.687C5.234 2.271 6.536 2 8 2s2.766.27 3.682.687C12.644 3.125 13 3.627 13 4c0 .374-.356.875-1.318 1.313C10.766 5.729 9.464 6 8 6s-2.766-.27-3.682-.687C3.356 4.875 3 4.373 3 4c0-.374.356-.875 1.318-1.313ZM13 5.698V7c0 .374-.356.875-1.318 1.313C10.766 8.729 9.464 9 8 9s-2.766-.27-3.682-.687C3.356 7.875 3 7.373 3 7V5.698c.271.202.58.378.904.525C4.978 6.711 6.427 7 8 7s3.022-.289 4.096-.777A4.92 4.92 0 0 0 13 5.698ZM14 4c0-1.007-.875-1.755-1.904-2.223C11.022 1.289 9.573 1 8 1s-3.022.289-4.096.777C2.875 2.245 2 2.993 2 4v9c0 1.007.875 1.755 1.904 2.223C4.978 15.71 6.427 16 8 16s3.022-.289 4.096-.777C13.125 14.755 14 14.007 14 13V4Zm-1 4.698V10c0 .374-.356.875-1.318 1.313C10.766 11.729 9.464 12 8 12s-2.766-.27-3.682-.687C3.356 10.875 3 10.373 3 10V8.698c.271.202.58.378.904.525C4.978 9.71 6.427 10 8 10s3.022-.289 4.096-.777A4.92 4.92 0 0 0 13 8.698Zm0 3V13c0 .374-.356.875-1.318 1.313C10.766 14.729 9.464 15 8 15s-2.766-.27-3.682-.687C3.356 13.875 3 13.373 3 13v-1.302c.271.202.58.378.904.525C4.978 12.71 6.427 13 8 13s3.022-.289 4.096-.777c.324-.147.633-.323.904-.525Z"/>
              </svg>
            <% end %>
          </span>
        </div>
        <%= form.submit "Search", style: "display: none;" %>
      <% end %>
      <p class="lead text-center"><%= @forecast_data[:location] || @forecast_data[:error] %></p>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6 col-xl-4">
      <% @forecast_data[:days].each do |forecast_day| %>
        <div class="card mt-4">
          <div class="card-header forecast-card-header">
            <div class="row">
              <div class="col">
                <h3><%= forecast_day[:day] %></h3>
              </div>
              <div class="col text-end red-color">
                <h3><%= forecast_day[:current_temp] %></h3>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <img src=<%= forecast_day[:condition][:icon] %> class="img-fluid" alt=<%= forecast_day[:condition][:text] %>>
                <span><%= forecast_day[:condition][:text].titleize %></span>
              </div>
              <div class="col text-end">
                <h6>Low <%= forecast_day[:low_temp] %></h6>
                <h6>High <%= forecast_day[:hi_temp] %></h6>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="row text-center">
              <% forecast_day[:hour].each do |forecast_hour| %>
                <div class="col">
                  <p class="card-text hourly-card-text"><%= forecast_hour[:time] %></p>
                  <img src=<%= forecast_hour[:condition][:icon] %> class="img-fluid" alt=<%= forecast_hour[:condition][:text] %>>
                  <p class="card-text"><%= forecast_hour[:temp] %></p>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherForcast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>